config/routes.rb
Rails.application.routes.draw do
  root to: 'bank_accounts#index'
  resources :expenses
  resources :bank_accounts do
    resources :expense_allocations
    resources :transactions, except: [:index, :show]
    resources :bank_transactions do
      post 'import', on: :collection
      patch 'reconcile', on: :member
    end
  end
  get '/sign_out', to: 'clearance/sessions#destroy', as: 'sign_out_get'
end

app/controllers/bank_transactions_controller.rb
class BankTransactionsController < ApplicationController
  before_action :set_bank_transaction, only: [:show, :edit, :update, :destroy, :reconcile]
  before_action :set_bank_account
  before_action :set_starting_from, only: :index

  def index
    bank_transactions = @bank_account.bank_transactions.starting_from(@starting_from)
    @bank_transactions = AddTransactionSuggestions
      .for_bank_transactions(@bank_account.trans, bank_transactions)
  end

  def show
  end

  def new
    @bank_transaction = BankTransaction.new
  end

  def edit
  end

  def create
    @bank_transaction = BankTransaction.new(bank_transaction_params)

    respond_to do |format|
      if @bank_transaction.save
        format.html { redirect_to @bank_transaction, notice: 'Bank transaction was successfully created.' }
        format.json { render :show, status: :created, location: @bank_transaction }
      else
        format.html { render :new }
        format.json { render json: @bank_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @bank_transaction.update(bank_transaction_params)
        format.html { redirect_to bank_account_bank_transactions_path(@bank_account), notice: 'Bank transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: [@bank_account, @bank_transaction] }
      else
        format.html { render :edit }
        format.json { render json: @bank_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def reconcile
    respond_to do |format|
      if @bank_transaction.reconcile!(reconcile_params)
        format.js { render 'bank_transactions/show_reconciled' }
      else
        @bank_transaction
      end
    end
  end

  def destroy
    @bank_transaction.destroy
    respond_to do |format|
      format.html { redirect_to bank_transactions_url, notice: 'Bank transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    BulkCreateBankTransactions.from_fnb_csv(@bank_account, import_params[:data].lines)
    redirect_to bank_account_bank_transactions_url(@bank_account), notice: 'Transactions successfully imported'
  end

  private
    def set_bank_transaction
      @bank_transaction = BankTransaction.find(params[:id])
    end

    def set_bank_account
      @bank_account = BankAccount.find(params[:bank_account_id])
    end

    def set_starting_from
      @starting_from = Date.parse(params[:starting_from]) rescue Date.today - 7.days
    end

    def bank_transaction_params
      params.require(:bank_transaction).permit(:processed_on, :description, :amount)
    end

    def import_params
      params.permit(:data)
    end

    def reconcile_params
      params.require(:bank_transaction).permit(:transaction_id)
    end
end

app/helpers/bank_transactions_helper.rb
module BankTransactionsHelper
  def bank_transaction_class(transaction, klass='')
    classes = [klass, 'statement-line', 'transaction']

    if transaction.reconciled?
      classes << 'reconciled'
    else
      classes << 'unreconciled'
    end

    if transaction.amount.positive? 
      classes << 'positive'
    else
      classes << 'negative'
    end
  end
end

app/views/bank_transactions/_bank_transaction.html.erb
  <%= link_to(
  edit_bank_account_bank_transaction_path(bank_account, bank_transaction), 
  class: bank_transaction_class(bank_transaction, 'pure-g'),
  'data-id' => bank_transaction.id,
) do %>
  <div class='pure-u-1'>
    <div class="bank-transaction-row">
      <div class="date"><%= bank_transaction.processed_on.to_date.to_s(:db) %></div>
      <div class="amount"><%= number_to_currency(bank_transaction.amount) %></div>
    </div>
    <div class="bank-transaction-row">
      <div class="description"><%= bank_transaction.description %></div>
    </div>
  </div>
  <% unless bank_transaction.reconciled? %>
    <%= form_for [bank_account, bank_account.trans.build], 
        html: { class: 'transaction-create-form' } do |f| %>
      <%= f.hidden_field :amount, value: bank_transaction.amount.to_s %>
      <%= f.hidden_field :processed_on, value: bank_transaction.processed_on %>
      <%= f.hidden_field :description, value: bank_transaction.description %>
      <%= hidden_field_tag :bank_transaction_id, bank_transaction.id %>
      <div class='button primary-action create-transaction-button'>
        <div>+ Create Transaction</div>
      </div>
    <% end %>
    <% bank_transaction.suggestions.each do |suggestion| %>
    <%= form_for [bank_account, bank_transaction],
      url: reconcile_bank_account_bank_transaction_path(bank_account, bank_transaction),
      remote: true,
      html: {
        'data-transaction-id' => bank_transaction.id,
        'data-suggestion-id' => suggestion.id,
        class: 'transaction-reconciliation-form'
      } do |f| %>
        <%= f.hidden_field :transaction_id, value: suggestion.id %>
        <div class='button reconcile-button secondary-action'>
          <div class="row">
            <div class="date"><%= suggestion.processed_on.to_date.to_s(:db) %></div>
            <div class="amount"><%= number_to_currency(suggestion.amount) %></div>
          </div>
          <div class="row">
            <div class="description"><%= suggestion.description %></div>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/bank_transactions/_form.html.erb
<%= form_for([@bank_account, bank_transaction]) do |f| %>
  <% if bank_transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bank_transaction.errors.count, "error") %> prohibited this bank_transaction from being saved:</h2>

      <ul>
      <% bank_transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :processed_on %>
    <%= f.date_select :processed_on %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>

  <div class="actions">
    <%= f.submit class: 'primary' %>
  </div>
<% end %>

app/views/bank_transactions/edit.html.erb
<%= content_for :nav do %>
  <div><%= link_to "Back", bank_account_bank_transactions_path(@bank_account) %></div>
  <div class="active">Edit Transaction</div>
  <div></div>
<% end %>

<%= render 'form', bank_transaction: @bank_transaction %>

app/views/bank_transactions/index.html.erb
<%= content_for :nav do %>
  <div><%= link_to "Home", root_path %></div>
  <div class="active"><%= @bank_account.name %></div>
  <div><%= link_to "Budget", @bank_account %></div>
<% end %>
<div class="bank-transactions">
<%= render partial: 'bank_transaction', 
  collection: @bank_transactions, 
  locals: { bank_account: @bank_account }
%>
</div>

<%= link_to "Show More", 
            bank_account_bank_transactions_path(@bank_account, 
                                                starting_from: @starting_from - 1.month),
            class: 'primary-action button' %>

<h2>Import Transactions</h2>
<%= form_tag import_bank_account_bank_transactions_path(@bank_account) do %>
  <%= text_area_tag :data %>
  <%= submit_tag 'Import', class:'primary-action button' %>
<% end %>


<script type="application/javascript">
  $('.reconcile-button').on('click', function(event) {
    event.stopPropagation();
    $(event.currentTarget)
      .closest('.transaction-reconciliation-form')
      .trigger('submit.rails');
  });

  $('.create-transaction-button').on('click', function(event) {
    event.stopPropagation();
    $(event.currentTarget).closest('.transaction-create-form').submit();
    return false;
  });
</script>

app/views/bank_transactions/new.html.erb
<h1>New Bank Transaction</h1>

<%= render 'form', bank_transaction: @bank_transaction %>

<%= link_to 'Back', bank_transactions_path %>

app/views/bank_transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Processed on:</strong>
  <%= @bank_transaction.processed_on %>
</p>

<p>
  <strong>Description:</strong>
  <%= @bank_transaction.description %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @bank_transaction.amount %>
</p>

<%= link_to 'Edit', edit_bank_transaction_path(@bank_transaction) %> |
<%= link_to 'Back', bank_transactions_path %>

app/views/bank_transactions/show_reconciled.js.erb
(function() {
  const transaction = document.querySelector('.transaction[data-id="<%=@bank_transaction.id%>"]');
  const options = document.querySelectorAll('[data-transaction-id="<%=@bank_transaction.id%>"]');

  const message = document.createElement('div');
  message.className = 'reconciliation-message';
  message.innerText = 'Successfully Reconciled';

  const otherSuggestions = document.querySelectorAll('[data-suggestion-id="<%=@bank_transaction.transaction_id%>"]')

  options.forEach(o => o.remove());
  otherSuggestions.forEach(s => s.remove());
  transaction.parentNode.insertBefore(message, transaction.nextSibling);
  transaction.classList.remove('unreconciled');
  transaction.classList.add('reconciled');
})()