config/routes.rb
Rails.application.routes.draw do
  root to: 'bank_accounts#index'
  resources :expenses
  resources :bank_accounts do
    resources :expense_allocations
    resources :transactions, except: [:index, :show]
    resources :bank_transactions do
      post 'import', on: :collection
      patch 'reconcile', on: :member
    end
  end
  get '/sign_out', to: 'clearance/sessions#destroy', as: 'sign_out_get'
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  has_many :expense_allocations
  has_many :statement_lines
  has_many :bank_transactions
  has_many :trans, class_name: 'Transaction', inverse_of: :bank_account
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < AuthenticatedController
  before_action :set_bank_account, only: [:show, :edit, :update, :destroy]
  before_action :set_starting_from, only: :show

  def index
    @bank_accounts = BankAccount.all
  end

  def show
    @statement_lines = @bank_account
      .statement_lines
      .includes(trans: :bank_transaction, expense_allocation_transactions: { expense_allocation: :expense} )
      .starting_from(@starting_from)
      .references(:transactions)
      .order('statement_lines.processed_on, order_weight, statement_lines.amount')
      .reverse
    
    @upcoming_allocations = @bank_account
      .expense_allocations
      .includes(:expense)
      .with_remaining_balance
      .until(MonthEnd.next(@bank_account.month_end))
      .select("expense_allocations.*, eab.amount as remaining")
      .to_a
      .uniq(&:name)
  end

  def new
    @bank_account = BankAccount.new
  end

  def edit
  end

  def create
    @bank_account = BankAccount.new(bank_account_params)

    respond_to do |format|
      if @bank_account.save
        format.html { redirect_to bank_accounts_path, notice: 'Bank Account was successfully created.' }
        format.json { render :show, status: :created, location: @bank_account }
      else
        format.html { render :new }
        format.json { render json: @bank_account.errors, status: :unprocessable_entity }
      end
    end
  end

def update
    respond_to do |format|
      if @bank_account.update(bank_account_params)
        format.html { redirect_to bank_accounts_path, notice: 'Bank Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @bank_account }
      else
        format.html { render :edit }
        format.json { render json: @bank_account.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @bank_account.destroy
    respond_to do |format|
      format.html { redirect_to bank_accounts_url, notice: 'BankAccount was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_bank_account
      @bank_account = BankAccount.find(params[:id])
    end

    def set_starting_from
      @starting_from = Date.parse(params[:starting_from]) rescue Date.today - 7.days
    end

    def bank_account_params
      params.require(:bank_account).permit(:name, :credit, :overdraft)
    end
end

app/helpers/bank_accounts_helper.rb
module BankAccountsHelper
 def render_statement_line(line)
    case line.class_name
    when 'Transaction'
      render('transaction', transaction: line)
    when 'ExpenseAllocation'
      render('allocation', allocation: line)
    end
  end

  def statement_line_class(line, klass='')
    classes = [klass, 'statement-line']

    classes << 'statement-line-red' if (line.respond_to?(:available) and line.available) <= 0
    if line.reconciled?
      classes << 'reconciled'
    else
      classes << 'unreconciled'
    end

    classes.join(' ')
  end
end

app/views/bank_accounts/_allocation.html.erb
<%= link_to(
  edit_bank_account_expense_allocation_path(allocation.bank_account_id, allocation.id),
  class: statement_line_class(allocation)
) do %>  
  <div class="statement-line-details">
    <span class="amount text-right"><%= number_to_currency(allocation.amount) %></span>
    <span class="amount text-right"><%= number_to_currency(allocation.balance) %></span>
    <span class="amount text-right"><%= number_to_currency(allocation.available) %></span>
  </div>
  <div class='header'>
    <div><%= allocation.description %></div>
    <div>
      <svg class="icon icon-meter"><use xlink:href="#icon-meter"></use></svg>
      <%= allocation.processed_on.to_date.to_s(:db) %> 
    </div>
  </div>
<% end %>

app/views/bank_accounts/_form.html.erb
<%= form_for(bank_account, { html: { class: 'pure-form pure-form-stacked' } }) do |f| %>
  <% if bank_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bank_account.errors.count, "error") %> prohibited this bank account from being saved:</h2>

      <ul>
      <% bank_account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

    <div class="field">
    <%= f.label :credit %>
    <%= f.text_field :credit %>
  </div>

  <div class="actions">
    <%= f.submit class: 'pure-button pure-button-primary' %>
  </div>
<% end %>

app/views/bank_accounts/_transaction.html.erb
<%= link_to(
  edit_bank_account_transaction_path(transaction.bank_account_id, transaction.id), 
  class: statement_line_class(transaction) 
) do %>
  <div class="statement-line-details">
    <span class="amount text-right"><%= number_to_currency(transaction.amount) %></span>
    <span class="amount text-right"><%= number_to_currency(transaction.balance) %></span>
    <span class="amount text-right"><%= number_to_currency(transaction.available) %></span>
  </div>
  <div class='header'>
    <div><%= transaction.description %></div>
    <div>
      <svg class="icon icon-credit-card"><use xlink:href="#icon-credit-card"></use></svg>
      <%= transaction.processed_on.to_date.to_s(:db) %>
    </div>
    
    <span class="allocations">
      <% transaction.expense_allocation_transactions.each do |allocation| %>
        <span class="allocation">
          <%= allocation.name %>
        </span>
      <% end %>
    </span>
  </div>
<% end %>

app/views/bank_accounts/edit.html.erb
<h1>Editing Bank Account</h1>

<%= render 'form', bank_account: @bank_account %>

<%= link_to 'Show', @bank_account %> |
<%= link_to 'Destroy', bank_account, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/bank_accounts/index.html.erb
<div class="pure-g">
  <% @bank_accounts.each do |bank_account| %>
    <%= link_to bank_account, class: 'bank-account pure-u-8-24 pure-u-1' do %>
      <span class="name"><%= bank_account.name %></span>
    <% end %>
  <% end %>
</div>


<%= link_to 'New Account', new_bank_account_path, class: 'pure-button' %>

app/views/bank_accounts/new.html.erb
<h1>New Bank Account</h1>

<%= render 'form', bank_account: @bank_account %>

<%= link_to 'Back', bank_accounts_path %>

app/views/bank_accounts/show.html.erb
<%= content_for :nav do %>
  <div><%= link_to "Home", root_path %></div>
  <div class='active'><%= @bank_account.name %></div>

  <div><%= link_to "Bank", bank_account_bank_transactions_path(@bank_account) %></div>
<% end %>
<div class='account-actions'>
  <% @upcoming_allocations.each_with_index do |allocation, index| %>
    <%= link_to new_bank_account_transaction_path(@bank_account, expense_allocation_id: allocation.id),
                { class: "page-action action-color-#{(index % 4) + 1}" } do %>
      <span><%= allocation.name %></span>
      <span class="amount"><%= allocation.remaining %></span>
    <% end %>
  <% end %>
   
  <%= link_to 'Add Transaction',
              new_bank_account_transaction_path(@bank_account),
              { class: "page-action" } %>
  <%= link_to 'Add Allocation',
              new_bank_account_expense_allocation_path(@bank_account),
              { class: "page-action" } %>
</div>
<div class="statement-line-header">
  <span class='amount-header text-right'>Amount</span>
  <span class='amount-header text-right'>Balance</span>
  <span class='amount-header text-right'>Available</span>
</div>
<% @statement_lines.each do |line| %>
  <%= render_statement_line(line) %>
<% end %>
</table>

<%= link_to "+ Show More", 
            bank_account_path(@bank_account, starting_from: @starting_from - 1.month), 
            class: 'primary-action ' %>