config/routes.rb
Rails.application.routes.draw do
  root to: 'bank_accounts#index'
  resources :expenses
  resources :bank_accounts do
    resources :expense_allocations
    resources :transactions, except: [:index, :show]
    resources :bank_transactions do
      post 'import', on: :collection
      patch 'reconcile', on: :member
    end
  end
  get '/sign_out', to: 'clearance/sessions#destroy', as: 'sign_out_get'
end

app/controllers/transactions_controller.rb
class TransactionsController < AuthenticatedController
  before_action :set_bank_account
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  before_action :set_bank_transaction, only: :create

  def show
  end

  def new
    @transaction = @bank_account.trans.new(processed_on: Date.today, expense: true)
    if params[:expense_allocation_id]
      @expense_allocation = ExpenseAllocation.find(params[:expense_allocation_id])
      @transaction.description = @expense_allocation.name
      @transaction.expense_allocation_transactions.build(expense_allocation: @expense_allocation)
    end
  end

  def edit
    @suggestions = AddTransactionSuggestions.suggestions_for_transaction(@transaction, @bank_account.bank_transactions)
  end

  def create
    @transaction = @bank_account.trans.build(transaction_params)
    @transaction.bank_transaction = @bank_transaction
    invert_sign(@transaction)
    
    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @bank_account, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @bank_account, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to @bank_account, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    def set_bank_account
      @bank_account = BankAccount.find(params[:bank_account_id])
    end

    def set_bank_transaction
      @bank_transaction = @bank_account.bank_transactions.find(params[:bank_transaction_id]) if params.key?(:bank_transaction_id)
    end

    def invert_sign(transaction)
      transaction.amount = -transaction.amount.abs if transaction.expense == true
    end

    def transaction_params
      params
        .require(:transaction)
        .permit(
          :description, 
          :amount,
          :processed_on,
          :expense,
          :bank_account_id,
          expense_allocation_transactions_attributes: [
            :id, :_destroy, :amount, :expense_allocation_id
          ]
      )
    end
end

app/views/transactions/_expense_allocation_transaction_fields.html.erb
<div class="nested-fields pure-form-stacked statement-line">
  <div class="pure-g">
    <div class="pure-u-1 pure-u-md-1-3">
      <%= f.collection_select(
        :expense_allocation_id,
        ExpenseAllocation.all,
        :id,
        :name,
        { prompt: 'Please select Expense' },
        { class: 'pure-input-1' }
      )
      %>
    </div>
    <div class="pure-u-1 pure-u-md-1-3">
      <%= f.text_field :amount, class: 'pure-input-1' %>
    </div>
    <div class="pure-u-1 pure-u-md-1-3 text-right">
      <%= link_to_remove_association "Remove", f, class: 'pure-button pure-button-cancel' %>
    </div>
  </div>
</div>

app/views/transactions/_form.html.erb
<%= form_for([bank_account, transaction], { html: { class: 'pure-form pure-form-stacked' } }) do |f| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :processed_on %>
    <%= f.date_field :processed_on %>
  </div>
  <hr />
  <div id="expense-transaction-allocations">
    <%= f.fields_for :expense_allocation_transactions do |allocation| %>
     <%= render 'expense_allocation_transaction_fields', :f => allocation %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'Add Allocation', f, :expense_allocation_transactions %>
    </div>
  </div>
  <div class="field">
    <%= f.label :expense do %>
      <%= f.check_box :expense %>
      Expense?
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit class: 'primary'%>
  </div>
<% end %>
<script type="text/javascript">
  (function () {
    var touched = false;
    
    function syncAmounts(e) {
      var count = $('.nested-fields').length;
      if (!touched && count === 1) {
        $('.nested-fields input[type="text"]')
          .val(Math.abs(parseFloat(e.target.value)));
      }
    }

    function markAsTouched() { touched = true; }

    $('form#new_transaction').on('keyup', 'input#transaction_amount', syncAmounts);
    $('form#new_transaction').on('keyup', '.nested-fields input[type="text"]', markAsTouched);
  })();
</script>

app/views/transactions/edit.html.erb
<%= content_for :nav do %>
  <div><%= link_to "Back", bank_account_path(@bank_account) %></div>
  <div class="active">Edit Transaction</div>
  <div></div>
<% end %>

<%= render 'form', bank_account: @bank_account, transaction: @transaction %>

<%= link_to 'Delete', [@bank_account, @transaction], method: :delete, data: { confirm: 'Are you sure?'}, class: 'pure-button'  %>

<% unless @transaction.reconciled? %>
  <h3>Suggestions</h3>
  <% @suggestions.each do |suggestion| %>
    <%= suggestion.description %>
  <% end %>
<% end %>

app/views/transactions/new.html.erb
<%= content_for :nav do %>
  <div><%= link_to "Back", bank_account_path(@bank_account) %></div>
  <div class="active">New Transaction</div>
  <div></div>
<% end %>


<%= render 'form', transaction: @transaction, bank_account: @bank_account %>